# Generated by Django 5.1.1 on 2024-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_maker', '0003_group_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Group Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
