# Generated by Django 5.1.1 on 2024-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_maker', '0006_alter_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
