# Generated by Django 5.1.1 on 2024-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_maker', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
