# Generated by Django 5.1.1 on 2024-12-17 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('bio', models.TextField(blank=True, verbose_name='About myself')),
                ('profile_image', models.ImageField(blank=True, upload_to='users/img', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
